//////////////////////////////////////////////////////////////////////////

; 积分游戏等级定义

//////////////////////////////////////////////////////////////////////////

[LevelDescribe]
LevelItem1=义务兵
LevelItem2=列兵,100
LevelItem3=二等兵,1000
LevelItem4=三等兵,10000
LevelItem5=四等兵,100000
LevelItem6=五等兵,200000
LevelItem7=六等兵,400000
LevelItem8=少尉,800000
LevelItem9=中尉,1000000
LevelItem10=上尉,3000000
LevelItem11=少校,5000000
LevelItem12=中校,7500000
LevelItem13=上校,10000000
LevelItem14=大校,15000000
LevelItem15=少将,25000000
LevelItem16=中将,50000000
LevelItem17=上将,100000000
LevelItem18=大将,250000000
LevelItem19=元帅,500000000
//////////////////////////////////////////////////////////////////////////